Repository wecode-bootcamp-korea/13-stayWefolio-frontend, pull requests merged in 2020-10, with the labels that each got.

#1 [stayWefolio 서수연] Add: Nav layout 작성
  package-lock.json
  package.json
  public/data/dataSSY/data.json
  public/data/dataSSY/navdata.json
  public/images/branchimg.png
  public/images/facebookimg.png
  public/images/instaimg.png
  public/images/logo.png
  public/images/naverimg.png
  public/images/youtubeimg.png
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/index.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#3 [Staywefolio 김보라] Fix: 메인페이지 conflict 해결
  package-lock.json
  package.json
  public/data/mainData/mainBannerData.json
  public/data/mainData/mainMagazineData.json
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainComponent/MainBottomCard/MainBottomCard.js
  src/pages/Main/MainComponent/MainBottomCard/MainBottomCard.scss
  src/pages/Main/MainComponent/MainHeader/MainHeader.js
  src/pages/Main/MainComponent/MainHeader/MainHeader.scss
  src/pages/Main/MainComponent/MainMagazine/MainMagazine.js
  src/pages/Main/MainComponent/MainMagazine/MainMagazine.scss
  src/styles/common.scss
Labels: Status: 리뷰 요청

#4 [Staywefolio 민지연] Add : input의 조건식에 따른 button 활성화 구현
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: Status: 컨플릭트 해결 요청

#5 [Staywefolio 민지연] Add : component 분리, 전체 checkbox 체크 구현
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/pages/Signup/signupComponent/Toggle.js
  src/pages/Signup/signupComponent/Vehicles.js
  src/pages/Signup/signupComponent/Vehicles.scss
Labels: Status: 컨플릭트 해결 요청

#6 [stayWefolio 신은선] Add: pagination 기능 추가 및 리팩토링, conflict 해결
  public/data/pickData/filterList_data.json
  public/data/pickData/hotels_data.json
  public/images/pickImg/pick_resort.jpg
  public/images/staywefolio_logo.png
  src/.eslintrc.json
  src/Routes.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/index.js
  src/pages/Pick/PageButton/PageButton.js
  src/pages/Pick/PageButton/PageButton.scss
  src/pages/Pick/Pick.js
  src/pages/Pick/Pick.scss
  src/pages/Pick/PickArticle/PickArticle.js
  src/pages/Pick/PickArticle/PickArticle.scss
  src/pages/Pick/SearchFilter/SearchFilter.js
  src/pages/Pick/SearchFilter/SearchFilter.scss
  src/pages/Pick/SearchFilterOption/SearchFilterOption.js
  src/pages/Pick/SearchFilterOption/SearchFilterOption.scss
  src/pages/Reservation/Reservation.js
  src/pages/Reservation/Reservation.scss
  src/styles/common.scss
Labels: Status: 리뷰 요청

#7 [stayWefolio 서수연] Add: 검색 기능 구현
  debug.log
  public/data/dataSSY/navdata.json
  public/images/logo.png
  pull_request_template.md
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/navLogin/NavLogin.js
  src/components/Nav/navLogin/NavLogin.scss
Labels: Status: 도움 요청, Status: 수정 요청

#10 [Staywefolio 김보라] Modify: booking 상세페이지 리뷰 반영 리팩토링 완료
  package-lock.json
  package.json
  public/data/bookingDetailData/roomBottomData.json
  public/data/bookingDetailData/roomInfoData.json
  public/index.html
  src/Routes.js
  src/components/Footer/Footer.js
  src/config.js
  src/pages/BookingDetail/BookingDetail.js
  src/pages/BookingDetail/BookingDetail.scss
  src/pages/BookingDetail/BookingDetailComponent/RoomsImgSlider/RoomImgSlider.scss
  src/pages/BookingDetail/BookingDetailComponent/RoomsImgSlider/RoomsImgSlider.js
  src/pages/BookingDetail/BookingDetailComponent/RoomsSlider/RoomsSlider.js
  src/pages/BookingDetail/BookingDetailComponent/RoomsSlider/RoomsSlider.scss
Labels: Status: Accepted

#12 [Staywefolio 김보라] Fix: 예약 확인 페이지 conflict 해결
  public/data/checkPageData/bookingData.json
  src/Routes.js
  src/pages/CheckPage/CheckPage.js
  src/pages/CheckPage/CheckPage.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainComponent/MainBottomCard/MainBottomCard.scss
  src/pages/Main/MainComponent/MainMagazine/MainMagazine.js
  src/pages/Pick/Pick.js
Labels: Status: 리뷰 요청

#11 [staywefolio 민지연] Modify : booking 메인페이지 conflict 해결
  src/Routes.js
  src/components/Nav/Nav.scss
  src/pages/Booking/Booking.js
  src/pages/Booking/Booking.scss
Labels: Status: Accepted

#14 [stayWEfolio 신은선] FIX: 코드리뷰 반영 리팩토링
  package-lock.json
  package.json
  public/data/dataSSY/navdata.json
  public/data/pickData/hotels_data.json
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/index.js
  src/pages/BookingDetail/BookingDetail.js
  src/pages/BookingDetail/BookingDetail.scss
  src/pages/BookingDetail/BookingDetailComponent/RoomsSlider/RoomsSlider.js
  src/pages/Login/Login.scss
  src/pages/Pick/PageButton/PageButton.js
  src/pages/Pick/PageButton/PageButton.scss
  src/pages/Pick/Pick.js
  src/pages/Pick/Pick.scss
  src/pages/Pick/PickArticle/PickArticle.js
  src/pages/Pick/PickArticle/PickArticle.scss
  src/pages/Pick/SearchFilter/SearchFilter.js
  src/pages/Pick/SearchFilter/SearchFilter.scss
  src/pages/Pick/SearchFilterOption/SearchFilterOption.js
  src/pages/Pick/SearchFilterOption/SearchFilterOption.scss
  src/pages/Reservation/AdditionalOption/AdditionalOption.js
  src/pages/Reservation/AdditionalOption/AdditionalOption.scss
  src/pages/Reservation/Information/Information.js
  src/pages/Reservation/Information/Information.scss
  src/pages/Reservation/PeopleOption/PeopleOption.js
  src/pages/Reservation/PeopleOption/PeopleOption.scss
  src/pages/Reservation/Reservation.js
  src/pages/Reservation/Reservation.scss
  src/pages/Reservation/ReservationInput/ReservationInput.js
  src/pages/Reservation/ReservationInput/ReservationInput.scss
  src/pages/Reservation/reservationData.js
  src/pages/Signup/Signup.scss
Labels: Status: 리뷰 요청

#19 [Staywefolio 김보라] Add: booking 상세페이지 하단 지도 추가
  package-lock.json
  package.json
  public/data/bookingDetailData/mapLocationData.json
  src/Routes.js
  src/components/Nav/Nav.js
  src/index.js
  src/pages/BookingDetail/BookingDetail.js
  src/pages/BookingDetail/BookingDetail.scss
  src/pages/BookingDetail/BookingDetailComponent/Map/MapContent.js
  src/pages/BookingDetail/BookingDetailComponent/Map/MapContent.scss
  src/pages/BookingDetail/BookingDetailComponent/RoomsSlider/RoomsSlider.scss
  src/pages/Reservation/Reservation.js
Labels: Status: 리뷰 요청

#20 [stayWefolio 서수연] Modify: 메뉴 버튼 수정
  .gitignore
  debug.log
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/index.js
  src/pages/Pick/Pick.scss
  src/pages/Reservation/Reservation.scss
Labels: Status: 리뷰 요청

#22 [stayWefolio 신은선] Add: 예약 로직 추가 및 conflict 해결
  src/Routes.js
  src/pages/BookingDetail/BookingDetail.js
  src/pages/BookingDetail/BookingDetailComponent/RoomsSlider/RoomsSlider.js
  src/pages/CheckPage/CheckPage.js
  src/pages/Login/Login.js
  src/pages/Reservation/Reservation.js
  src/pages/Reservation/ReservationInput/ReservationInput.js
  src/pages/Reservation/reservationData.js
  src/pages/Signup/Signup.js
Labels: Status: 리뷰 요청

#16 [staywefolio 민지연] 리뷰 반영 수정 완료
  src/Routes.js
  src/pages/Reservation/ReservationInfo/ReservationInfo.js
  src/pages/Reservation/ReservationInfo/ReservationInfo.scss
  src/pages/Reservation/ReservationInfo/ReservationInfoComponent/ReservationInfoData.js
  src/pages/Reservation/ReservationInfo/ReservationInfoComponent/ReservationInfoToggle.js
  src/pages/Reservation/ReservationInfo/ReservationInfoComponent/ReservationInfoVehicles.js
  src/pages/Reservation/ReservationInfo/ReservationInfoComponent/ReservationInfoVehicles.scss
Labels: Status: 리뷰 요청

#21 [Staywefolio 김보라] Add: booking 페이지 유동라우터 추가 + conflict 해결
  src/index.js
  src/pages/Booking/Booking.js
  src/pages/BookingDetail/BookingDetail.scss
  src/pages/BookingDetail/BookingDetailComponent/RoomsImgSlider/RoomImgSlider.scss
  src/pages/Main/Main.js
  src/pages/Pick/Pick.js
  src/pages/Pick/PickArticle/PickArticle.js
Labels: Status: 리뷰 요청

#23 Modify: page 전체 레이아웃과 기능 확인 및 수정
  public/data/dataSSY/footer.json
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Booking/Booking.js
  src/pages/Booking/Booking.scss
  src/pages/Reservation/AdditionalOption/AdditionalOption.js
  src/pages/Reservation/AdditionalOption/AdditionalOption.scss
  src/pages/Reservation/Reservation.js
  src/pages/Reservation/Reservation.scss
  src/pages/Reservation/ReservationInfo/ReservationInfo.js
  src/pages/Reservation/ReservationInfo/ReservationInfo.scss
  src/pages/Reservation/ReservationInfo/ReservationInfoComponent/ReservationInfoVehicles.scss
  src/pages/Signup/Signup.js
Labels: Status: 리뷰 요청
